apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tcprecon-pvc
  namespace: asm-secops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tcprecon-engine
  namespace: asm-secops
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            fsGroup: 10001
          imagePullSecrets:
          - name: ghcr-secret
          containers:
          - name: tcprecon
            image: ghcr.io/crytosky1324/tcprecon:latest
            imagePullPolicy: IfNotPresent
            args: ["-j", "https://gist.githubusercontent.com/CryToSky1324/4280ac414df4c3f9398657b5344977f1/raw/a89ce59170d8d2d51212f847c2a51c4dd685129f/gistfile1.txt"]
            env:
            - name: DB_PATH
              value: "/data/asm_state.db"
            volumeMounts:
            - name: bbolt-data
              mountPath: /data
            resources:
              requests:
                cpu: "500m"
                memory: "256Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"
          restartPolicy: OnFailure
          volumes:
          - name: bbolt-data
            persistentVolumeClaim:
              claimName: tcprecon-pvc
